# Generated by Django 6.0.5 on 2026-06-03 21:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_rename_tiktok_socialmedia_twitter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('sku_code', models.CharField(max_length=100, unique=True)),
                ('barcode_ean', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(choices=[('serum', 'Serum'), ('moisturiser', 'Moisturiser'), ('cleanser', 'Cleanser'), ('spf', 'SPF / Sun Care'), ('eye_care', 'Eye Care'), ('body_care', 'Body Care'), ('mask', 'Mask'), ('other', 'Other')], default='serum', max_length=30)),
                ('pack_size', models.CharField(choices=[('30ml', '30 ml'), ('50ml', '50 ml'), ('100ml', '100 ml'), ('150ml', '150 ml'), ('200ml', '200 ml'), ('custom', 'Custom')], default='50ml', max_length=20)),
                ('retail_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/images/')),
                ('compliance_status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('compliance_health_score', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='users.partnerprofile')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products_product',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BatchRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_code', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('manufacturing_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='products.product')),
            ],
            options={
                'verbose_name': 'Batch Record',
                'verbose_name_plural': 'Batch Records',
                'db_table': 'products_batch_record',
                'ordering': ['-manufacturing_date'],
            },
        ),
    ]
