# Generated by Django 6.0.5 on 2026-06-10 00:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedLogisticDoc',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('destination_country', models.CharField(choices=[('eu', 'EU (Intra-EU)'), ('usa', 'USA'), ('uae', 'UAE'), ('singapore', 'Singapore'), ('japan', 'Japan')], max_length=50)),
                ('document_type', models.CharField(choices=[('commercial_invoice', 'Commercial Invoice'), ('packing_list', 'Packing List'), ('certificate_of_origin', 'Certificate of Origin'), ('export_declaration', 'Export Declaration')], max_length=50)),
                ('file', models.FileField(blank=True, null=True, upload_to='logistics/generated_docs/')),
                ('file_url', models.URLField(blank=True, max_length=500)),
                ('file_size_text', models.CharField(default='PDF - 124 KB', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logistic_documents', to='products.product')),
            ],
            options={
                'verbose_name': 'Global Logistics Partner Doc',
                'verbose_name_plural': 'Global Logistics Partner Docs',
                'db_table': 'logistics_generated_document',
                'ordering': ['-created_at'],
            },
        ),
    ]
