# Generated by Django 6.0.5 on 2026-06-02 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_partnerprofile_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialmedia',
            old_name='tiktok',
            new_name='twitter',
        ),
    ]
