# Generated by Django 6.0.5 on 2026-06-23 15:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_rename_tiktok_socialmedia_twitter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('scheduled_datetime', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('jitsi_room_name', models.CharField(blank=True, max_length=150, unique=True)),
                ('invited_emails', models.JSONField(blank=True, default=list)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_meetings', to='users.partnerprofile')),
            ],
            options={
                'db_table': 'meetings_meeting',
                'ordering': ['scheduled_datetime'],
            },
        ),
    ]
