# Generated by Django 6.0.5 on 2026-06-10 01:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0003_rename_tiktok_socialmedia_twitter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChemistChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chemist_sessions', to='users.partnerprofile')),
            ],
            options={
                'db_table': 'ai_chemist_session',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChemistMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('model', 'Model')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_engine.chemistchatsession')),
            ],
            options={
                'db_table': 'ai_chemist_message',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForecastRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accuracy', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quarter', models.CharField(max_length=20)),
                ('trend_points', models.JSONField(default=list)),
                ('inventory_risk', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=10)),
                ('demand_volatility', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=10)),
                ('supply_chain_risk', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=10)),
                ('summary', models.TextField(blank=True)),
                ('model_version', models.CharField(default='Kanzen Forecast v2.3', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='users.partnerprofile')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='products.product')),
            ],
            options={
                'db_table': 'ai_forecast_record',
                'ordering': ['-created_at'],
            },
        ),
    ]
