# Generated by Django 6.0.5 on 2026-06-11 00:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0003_rename_tiktok_socialmedia_twitter'),
    ]

    operations = [
        migrations.CreateModel(
            name='COGSimulation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tiers', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cog_simulations', to='users.partnerprofile')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cog_simulations', to='products.product')),
            ],
            options={
                'db_table': 'growth_cog_simulation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarginCalculation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('production_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('packaging_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('marketing_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('profit_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('margin_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='margin_calculations', to='users.partnerprofile')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='margin_calculations', to='products.product')),
            ],
            options={
                'db_table': 'growth_margin_calculation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedFormulation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('skin_type', models.CharField(blank=True, max_length=100)),
                ('concern', models.CharField(blank=True, max_length=100)),
                ('product_format', models.CharField(blank=True, max_length=50)),
                ('formula_name', models.CharField(max_length=255)),
                ('base_formula', models.JSONField(default=list)),
                ('active_stack', models.JSONField(default=list)),
                ('est_moq', models.CharField(blank=True, max_length=50)),
                ('cost_per_unit', models.CharField(blank=True, max_length=50)),
                ('retail_range', models.CharField(blank=True, max_length=50)),
                ('key_benefits', models.JSONField(default=list)),
                ('ph_range', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_formulations', to='users.partnerprofile')),
            ],
            options={
                'db_table': 'growth_saved_formulation',
                'ordering': ['-created_at'],
            },
        ),
    ]
